# typed: false
# frozen_string_literal: true

# Generated by scripts/brew-formula.sh on release — edit that script, not this.
class Wallfacer < Formula
  desc "Terminal session manager for Claude Code, Cursor CLI, Kiro CLI and Codex"
  homepage "https://github.com/pradipta/wallfacer"
  version "1.2.1"
  license "MIT"

  # Pure Go, statically linked: nothing to depend on, nothing to build here.
  on_macos do
    on_arm do
      url "https://github.com/pradipta/wallfacer/releases/download/v1.2.1/wallfacer-darwin-arm64.tar.gz"
      sha256 "aef8c2c4c8d41df132c6b7a57583af2c4b3f65fa628bbdbf0a34fdeb1a4361cd"
    end
    on_intel do
      url "https://github.com/pradipta/wallfacer/releases/download/v1.2.1/wallfacer-darwin-amd64.tar.gz"
      sha256 "1d10bc4bd343b71728113593eb8b19f89d1e221c0647b23591fb314bfb60e9a8"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/pradipta/wallfacer/releases/download/v1.2.1/wallfacer-linux-arm64.tar.gz"
      sha256 "888f6c540497cd18fce3002aebc25ae7c7605cb2ce730eb42cb056d016687a4b"
    end
    on_intel do
      url "https://github.com/pradipta/wallfacer/releases/download/v1.2.1/wallfacer-linux-amd64.tar.gz"
      sha256 "902bb2f3203fe9ae345b49773f9feb3f6ffa9502eeff77d500b7f7fdefe325a2"
    end
  end

  def install
    bin.install "wallfacer"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/wallfacer --version")
  end
end
