# typed: false
# frozen_string_literal: true

# Generated by scripts/brew-formula.sh on release — edit that script, not this.
class Wallfacer < Formula
  desc "Terminal session manager for Claude Code, Cursor CLI, Kiro CLI and Codex"
  homepage "https://github.com/pradipta/wallfacer"
  version "1.2.2"
  license "MIT"

  # Pure Go, statically linked: nothing to depend on, nothing to build here.
  on_macos do
    on_arm do
      url "https://github.com/pradipta/wallfacer/releases/download/v1.2.2/wallfacer-darwin-arm64.tar.gz"
      sha256 "e1be3a40d9516c0e74ab56980d499f60c3e8eb999b9c953655b19dfac7113683"
    end
    on_intel do
      url "https://github.com/pradipta/wallfacer/releases/download/v1.2.2/wallfacer-darwin-amd64.tar.gz"
      sha256 "34cfbafab9b60dd168f83d003134d409c9ac0194797e32706e580d1015ec75cb"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/pradipta/wallfacer/releases/download/v1.2.2/wallfacer-linux-arm64.tar.gz"
      sha256 "e4ed583aa21e378891f86b9b13e0688d1c77b8452a5a1bc8f9cdc9899939c06d"
    end
    on_intel do
      url "https://github.com/pradipta/wallfacer/releases/download/v1.2.2/wallfacer-linux-amd64.tar.gz"
      sha256 "ebe4d32cbb17d8079eea79e15a1f4a9affa1e99426aa91e0fccb772ad751a54b"
    end
  end

  def install
    bin.install "wallfacer"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/wallfacer --version")
  end
end
