# typed: false
# frozen_string_literal: true

# Generated by scripts/brew-formula.sh on release — edit that script, not this.
class Wallfacer < Formula
  desc "Terminal session manager for Claude Code, Cursor CLI, Kiro CLI and Codex"
  homepage "https://github.com/pradipta/wallfacer"
  version "1.2.3"
  license "MIT"

  # Pure Go, statically linked: nothing to depend on, nothing to build here.
  on_macos do
    on_arm do
      url "https://github.com/pradipta/wallfacer/releases/download/v1.2.3/wallfacer-darwin-arm64.tar.gz"
      sha256 "6460965f52ab7fc822affcb02476dc33616cce1fc2765ef3e9ea2d140bcfa44f"
    end
    on_intel do
      url "https://github.com/pradipta/wallfacer/releases/download/v1.2.3/wallfacer-darwin-amd64.tar.gz"
      sha256 "270ca85129830594baa18ee7e990d9e8f78465962b020e598e7c9f79531a7d63"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/pradipta/wallfacer/releases/download/v1.2.3/wallfacer-linux-arm64.tar.gz"
      sha256 "ebae08b01042a548c8e772e9c8c116546e59b9df2efd639da5b776514d35c344"
    end
    on_intel do
      url "https://github.com/pradipta/wallfacer/releases/download/v1.2.3/wallfacer-linux-amd64.tar.gz"
      sha256 "de93dc1a584a091a8ab560b812b55764b1aacf340cb7c4ec17be83e96a3a1ea9"
    end
  end

  def install
    bin.install "wallfacer"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/wallfacer --version")
  end
end
