#!/usr/bin/env bash
#
# Print the Homebrew formula for a release, reading the archive checksums out of
# dist/checksums.txt (so `make release` has to have run first).
#
# The formula is generated rather than hand-maintained because Homebrew pins each
# download by sha256, and those checksums only exist once the release binaries
# have been built. `make brew-formula` writes the output to
# HomebrewFormula/wallfacer.rb, which is what `brew tap` reads.
#
#   usage: scripts/brew-formula.sh <tag> [dist-dir]
#
# BREW_BASE_URL overrides where the archives are fetched from; point it at
# file://$PWD/dist to install a formula straight out of a local build.

set -euo pipefail

tag=${1:?usage: brew-formula.sh <tag> [dist-dir]}
dist=${2:-dist}
version=${tag#v}
base=${BREW_BASE_URL:-https://github.com/pradipta/wallfacer/releases/download/$tag}

sums="$dist/checksums.txt"
[[ -f $sums ]] || {
	echo "brew-formula: $sums not found — run 'make release' first" >&2
	exit 1
}

# sha256 of one platform's archive. shasum and sha256sum agree on the
# "<hash>  <file>" format; the leading ./ is tolerated either way.
sha() {
	local file="wallfacer-$1.tar.gz" hash
	hash=$(awk -v f="$file" '$2 == f || $2 == "./" f { print $1 }' "$sums")
	[[ -n $hash ]] || {
		echo "brew-formula: no checksum for $file in $sums" >&2
		exit 1
	}
	echo "$hash"
}

cat <<FORMULA
# typed: false
# frozen_string_literal: true

# Generated by scripts/brew-formula.sh on release — edit that script, not this.
class Wallfacer < Formula
  desc "Terminal session manager for Claude Code, Cursor CLI, Kiro CLI and Codex"
  homepage "https://github.com/pradipta/wallfacer"
  version "$version"
  license "MIT"

  # Pure Go, statically linked: nothing to depend on, nothing to build here.
  on_macos do
    on_arm do
      url "$base/wallfacer-darwin-arm64.tar.gz"
      sha256 "$(sha darwin-arm64)"
    end
    on_intel do
      url "$base/wallfacer-darwin-amd64.tar.gz"
      sha256 "$(sha darwin-amd64)"
    end
  end

  on_linux do
    on_arm do
      url "$base/wallfacer-linux-arm64.tar.gz"
      sha256 "$(sha linux-arm64)"
    end
    on_intel do
      url "$base/wallfacer-linux-amd64.tar.gz"
      sha256 "$(sha linux-amd64)"
    end
  end

  def install
    bin.install "wallfacer"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/wallfacer --version")
  end
end
FORMULA
